### ISSUE TITLE
getting error on export scanplate

### ISSUE THREAD

**Issue by rnloyola** [Griefa/qb-platescan#2]
![image](https://github.com/Griefa/qb-platescan/assets/122580720/733bdaeb-08f2-44cf-982f-b33733335fac)

**Comment by rnloyola** [comment]
+ doesnt exist cl_extraevents just cl_extraalerts

**Comment by ImBeefy** [comment]
Did you get this to work. Im struggling with vehiclekeys and making car flag as stolen

**Comment by KEVI-exe** [comment]
> Did you get this to work. Im struggling with vehiclekeys and making car flag as stolen

me too

**Comment by KEVI-exe** [comment]
did you find out

**Comment by Griefa** [comment]
Just put it in the Hotwire event. Shouldn't be too difficult

**Comment by ImBeefy** [comment]
I did and its not making it flag as stolen.

**Comment by Griefa** [comment]
I dont use qb-vehiclekeys because its horse shit

**Comment by ImBeefy** [comment]
We can certainly agree on that lol. 
What do you use,? I

**Comment by Griefa** [comment]
https://mankind.tebex.io/package/5423031 

Hands down the best vehiclekey resource

**Comment by ImBeefy** [comment]
Would i be able to just replace my current with this?
and can it blacklist vehicles like PD, so people cant lockpick them :D?

**Comment by Griefa** [comment]
> Would i be able to just replace my current with this?
> and can it blacklist vehicles like PD, so people cant lockpick them :D?

Yes and yes. I suggest joining his discord and opening a ticket

**Comment by ImBeefy** [comment]
Thank you!
